### PR TITLE
#184 converted classic pipeline to yaml AWS - Build Cloud Account Id Artefacts 3.0 #193

### PR DESCRIPTION
**Pull request by priyadishah**
[https://github.com/https://github.com/robe070/cookbooks/issues/184]

converted classic pipeline to yaml pipeline, details are below.

Classic Pipeline
Repository: robe070/cookbooks
Branch: debug/paas
Pipeline Name - Build Cloud Account Id Artefacts

Converted classic to yaml pipeline
Repository: priyadishah/cookbooks
Branch: feature/aws-Build-Cloud-Account-Id-Artefacts-3.0
Pipeline Name: Build Cloud Account Id Artefacts 3.0
Pipeline Url: https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_build?definitionId=60

### CODE REVIEW

**Review by robe070 — CHANGES_REQUESTED** [review]
Why has this PR been raised on lansalpc/cookbooks?

**Comment by robe070** [comment]
You are using one PR for 2 pipelines: `Build Cloud Account Id Artefacts 3.0` and `AWS Cloud Account Id Image Release 3.0`.

They must be split up right now.

Lets get `Build Cloud Account Id Artefacts 3.0` completed. Raise another PR for `AWS Cloud Account Id Image Release 3.0`

**Comment by priyadishah** [comment]
> You are using one PR for 2 pipelines: `Build Cloud Account Id Artefacts 3.0` and `AWS Cloud Account Id Image Release 3.0`.
> 
> They must be split up right now.
> 
> Lets get `Build Cloud Account Id Artefacts 3.0` completed. Raise another PR for `AWS Cloud Account Id Image Release 3.0`

@robe070 there are different PRs for `Build Cloud Account Id Artefacts 3.0` and `AWS Cloud Account Id Image Release 3.0`
Build Cloud Account Id Artefacts 3.0 - https://github.com/robe070/cookbooks/pull/194
AWS Cloud Account Id Image Release 3.0 - https://github.com/robe070/cookbooks/pull/192

Here, I created this pull request under lansalpc/cookbooks instead of robe070/cookbooks.

**Comment by robe070** [comment]
You need to raise this pull request against robe070. I have been ignoring it, thinking it was a duplication.

**Comment by priyadishah** [comment]
This is merged with robe070 PR. https://github.com/robe070/cookbooks/pull/194

**Pull request closed without merging**
